apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
      - name: debezium-connect
        # image: debezium/connect:2.3
        # image: debezium/connect:2.7.3.Final
        image: debezium/connect:3.0.0.Final
        ports:
        - containerPort: 8083
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: "debezium-connect-configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "debezium-connect-offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "debezium-connect-status"
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect
  namespace: default
spec:
  selector:
    app: debezium-connect
  ports:
    - port: 8083
      targetPort: 8083
