apiVersion: batch/v1
kind: Job
metadata:
  name: register-debezium-connector
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: register-connector
        image: curlimages/curl
        command:
          - /bin/sh
          - -c
          - |
            # Debezium Connect가 뜰 때까지 대기
            until curl -s http://debezium-connect:8083/connectors > /dev/null; do
              echo "Waiting for Debezium Connect to be ready..."
              sleep 5
            done

            # Connector 등록
            curl -X POST -H "Content-Type: application/json" \
              -d '{
                "name": "outbox-connector",
                "config": {
                  "connector.class": "io.debezium.connector.mysql.MySqlConnector",
                  "database.hostname": "mysql-service",
                  "database.port": "3306",
                  "database.user": "root",
                  "database.password": "root",
                  "database.server.id": "184054",
                  "topic.prefix": "dbserver",
                  "database.server.name": "dbserver",
                  "database.include.list": "product_category",
                  "table.include.list": "product_category.outbox",
                  "schema.history.internal.kafka.bootstrap.servers": "kafka-service:9092",
                  "schema.history.internal.kafka.topic": "schema-changes.outbox",
                  "transforms": "outbox",
                  "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",
                  "transforms.outbox.route.by.field": "aggregatetype",
                  "transforms.outbox.route.topic.replacement": "${routedByValue}",
                  "transforms.outbox.route.key.field": "aggregateid",
                  "transforms.outbox.table.field.event.payload": "payload",
                  "transforms.outbox.table.fields.additional.placement": "type:header:eventType",
                  "errors.tolerance": "all",
                  "errors.log.enable": true,
                  "errors.log.include.messages": true,
                  "errors.deadletterqueue.topic.name": "outbox-dlq",
                  "errors.deadletterqueue.context.headers.enable": true,
                  "max.retries": 3,
                  "retry.backoff.ms": 1000
                }
              }' \
              http://debezium-connect:8083/connectors
