apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.0
          ports:
            - containerPort: 9092
              name: kafka-port
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xms512m -Xmx512m"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CONNECTIONS_MAX_IDLE_MS
              value: "600000"
            - name: KAFKA_SOCKET_CONNECTION_SETUP_TIMEOUT_MS
              value: "10000"
            - name: KAFKA_SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS
              value: "30000"
            - name: KAFKA_REPLICA_FETCH_WAIT_MAX_MS
              value: "500"
            - name: KAFKA_REPLICA_FETCH_MIN_BYTES
              value: "1"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "1048576"
            - name: KAFKA_NUM_NETWORK_THREADS
              value: "3"
            - name: KAFKA_NUM_IO_THREADS
              value: "8"
            - name: KAFKA_BACKGROUND_THREADS
              value: "10"
            - name: KAFKA_QUEUED_MAX_REQUESTS
              value: "500"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
  clusterIP: None
