apiVersion: v1
kind: ConfigMap
metadata:
  name: monstache-config
data:
  config.toml: |
    mongo-url = "mongodb://username:password@mongodb-service:27017/my_db?authSource=admin"
    elasticsearch-urls = ["http://elasticsearch-service:9200"]
    direct-read-namespaces = ["my_db.products"]
    namespace-regex = "my_db.products"
    verbose = true
    elasticsearch-max-conns = 4
    elasticsearch-max-seconds = 5
    elasticsearch-user = "elastic"
    elasticsearch-password = "changeme"
    elasticsearch-version = "8"
    dropped-collections = true
    dropped-databases = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstache
  template:
    metadata:
      labels:
        app: monstache
    spec:
      containers:
        - name: monstache
          image: rwynn/monstache:6
          args: ["-f", "/config/config.toml"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: monstache-config
---
apiVersion: v1
kind: Service
metadata:
  name: monstache-service
spec:
  selector:
    app: monstache
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080